### ISSUE TITLE
[BUG] - Unable to start module

### ISSUE THREAD

**Issue by jmcc94** [bitfocus/companion-module-renewedvision-propresenter-rest#14]
I'm testing this module locally with companion, and have place it the 'dev' folder, but the module doesn't want to start

The error in the log is - Instance/ModuleHost: Module entrypoint "G:\...\companion-module-renewedvision-propresenter-api\dist\main.js" does not exist

I also notice that package.json has `"main": "dist/index.js",`
&
manifest.json has `"entrypoint": "../dist/main.js"`

And there is no 'dist folder' in the module, but there is a `src/main.ts`

I assume it's mot meant to be like this?

Really keen to test this, but currently unable to...

**Comment by greyshirtguy** [comment]
It's not quite ready... It will be very soon and added to a beta..(a couple of weeks).

If you really want to test a pre-release... I've been putting them here as I work on it
[https://1drv.ms/f/s!ArHkDUamXNMvkuVDR_Yqk0RWDfg4aA?e=a4pdJY](https://1drv.ms/f/s!ArHkDUamXNMvkuVDR_Yqk0RWDfg4aA?e=a4pdJY&fbclid=IwZXh0bgNhZW0CMTAAAR1NjaXz92w0cDKBtkC1UaGHSHtBPdsNqeenS6p0FlmzplotmMSDI_iSWmI_aem_ANBAlLGz42MP9fVgYz9EFg)

**Comment by Joelneumann** [comment]
I have a question about the build process. I was able to test your module from the OneDrive Link. What do I have to do to build it by my own?

**Comment by greyshirtguy** [comment]
Checkout 
https://github.com/bitfocus/companion-module-base/wiki and 
https://github.com/bitfocus/companion-module-base/wiki/Module-development-101

Pay attention to the parts for cloning an existing module. (You want to clone this module: https://github.com/bitfocus/companion-module-renewedvision-propresenter-api)

Once cloned, don't forget to run yarn to install dependacies and then yarn build

**Comment by Joelneumann** [comment]
I already did that, but the output in the "dist" folder looked different from the folder in OneDrive. But I managed to get it also running in Companion. Thanks for your help.
